version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_DB=camfinDB
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_SERVER_URL=http://localhost:9000
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - minio
    env_file:
      - .env
    restart: unless-stopped